close all
clear all

%----Set Figure-----%
scrsz = get(0,'ScreenSize');
f =figure(1); set(f,'Visible','off','Position',[scrsz(3)/4 scrsz(4)/5 scrsz(3)/2 scrsz(4)/1.5],...
           'windowstyle', 'normal', 'resize', 'on','Visible','on');
%% 
htext1  = uicontrol('Parent',f,'Style','text','String','frames',...
             'Units','normalized',...
           'Position',[0.05 0.2 0.1 0.03]);
htext2  = uicontrol('Parent',f,'Style','text','String','exp.time',...
             'Units','normalized','Position',[0.05 0.15 0.1 0.03]);
htext3  = uicontrol('Parent',f,'Style','text','String','new folder',...
             'Units','normalized','Position',[0.05 0.1 0.1 0.03]);
htext4  = uicontrol('Parent',f,'Style','text','String','Last saved file : ',...
             'Units','normalized','Position',[0.05 0.01 0.35 0.03]);
htext5  = uicontrol('Parent',f,'Style','text','String','',...
             'Units','normalized','Position',[0.05 0.96 0.35 0.03]);
hedit1  = uicontrol('Parent',f,'Style','edit','String','',...
             'Units','normalized','Position',[0.17 0.2 0.1 0.025]);
hedit2  = uicontrol('Parent',f,'Style','edit','String','',...
             'Units','normalized','Position',[0.17 0.15 0.1 0.025]);     
hedit3  = uicontrol('Parent',f,'Style','edit','String','',...
             'Units','normalized','Position',[0.17 0.1 0.1 0.025]);  
hpanel1  = uipanel('Parent',f,'Title','comments',...
                  'visible', 'on' ,'Position',[0.3 0.08 0.2 0.15]);
hedit4  = uicontrol(hpanel1,'Style','edit','String','',...
           'visible', 'on' ,...
           'Units','normalized','Position',[0.005 0.01 1 1]);
           
hcheck4  = uicontrol('Parent',f,'Style','checkbox','String','overwrite',...
           'Units','normalized','Position',[0.17 0.05 0.1 0.04]); 
       

hgroup = uibuttongroup('Parent',f,'visible','on','Position',[0.5 0.08 0.1 0.1]);
u0 = uicontrol('Style','Radio','String','IC',...
    'Units','normalized',...
    'pos',[0.2 0.6 0.8 0.15],'parent',hgroup,'HandleVisibility','on');
u1 = uicontrol('Style','Radio','String','VC',...
    'Units','normalized',...
    'pos',[0.2 0.3 0.8 0.15],'parent',hgroup,'HandleVisibility','on');


htext1l  = uicontrol('Parent',f,'Style','text','String','frames',...
             'Units','normalized',...
           'Position',[0.6 0.2 0.1 0.03]);
htext2l  = uicontrol('Parent',f,'Style','text','String','exp.time',...
             'Units','normalized',...
           'Position',[0.6 0.15 0.1 0.03]);
htext3l  = uicontrol('Parent',f,'Style','text','String','shown folder',...
             'Units','normalized',...
           'Position',[0.6 0.1 0.1 0.03]);

hedit1l  = uicontrol('Parent',f,'Style','text','String','frames',...
             'Units','normalized','BackGroundColor',[0.7 0.8 0.9],...
           'Position',[0.7 0.2 0.1 0.03]);
hedit2l  = uicontrol('Parent',f,'Style','text','String','exp.time',...
             'Units','normalized','BackGroundColor',[0.7 0.8 0.9],...
           'Position',[0.7 0.15 0.1 0.03]);     
hedit3l  = uicontrol('Parent',f,'Style','text','String','current file:',...
             'Units','normalized','BackGroundColor',[0.7 0.8 0.9],...
           'Position',[0.7 0.1 0.1 0.03]);  
 fr_hold=0;

figure(1);subplot('Position',[0.1 0.3 0.85 0.3]);grid('on');ylabel('membrane current (A)');
figure(1);subplot('Position',[0.1 0.65 0.85 0.3]);grid('on'); ylabel('Membrane potential (V)');title('Preview Data ');

uicontrol(f,'Style','push','Units','normalized',...
 'String','Start','Position',[0.05 0.05 0.1 0.04],...
'Callback',['set(htext5,''String'','''');'...
'N=str2double(get(hedit1,''String''));'...
'dt=(str2double(get(hedit2,''String'')))/1000;'...
'com=get(hedit4,''String'');'...
's=daq.createSession(''ni'');'...
'addAnalogInputChannel(s,''Dev1'',0:2,''Voltage'');'...
'addAnalogOutputChannel(s,''Dev1'',0,''Voltage'');'...
's.Rate=20000;outputSingleValue=5;'...
'samples=s.Rate;F=1/dt;duration=(N*dt)+0.05;'...
'output_data=sin(linspace(0,2*pi,samples*duration)'')*0;'...
'output_data(1:10)=5;queueOutputData(s,output_data);'...
'[captured_data,time,trig]=s.startForeground();'...
'z=samples*duration;'...
'Ya=captured_data(:,1);Yb=captured_data(:,2);Yc=captured_data(:,3);'...
'if (get(u0,''Value'')==get(u0,''Max'')),YY1=Ya/0.01;YY2=Yb/0.5;Y3=Yc;'...
'elseif (get(u1,''Value'')==get(u1,''Max'')),'...
'YY2=Ya/0.5;YY1=Yb/0.01;Y3=Yc;end;'...
'TSTART=find(Y3>1);TSTART=TSTART(1);Y1=YY1(TSTART:TSTART+round(N*dt*20000)-1);'...
'Y2=YY2(TSTART:TSTART+round(N*dt*20000)-1);'...
'time1=time(TSTART:TSTART+round(N*dt*20000)-1);time1=time1-time1(1);'...
'if fr_hold==1, hold on; else,hold off;end;'...
'figure(1);subplot(''Position'',[0.1 0.3 0.85 0.3]);plot(time1,Y2);grid(''on'');ylabel(''membrane current (A)'');xlabel(''time'');'...
'figure(1);subplot(''Position'',[0.1 0.65 0.85 0.3]);plot(time1,Y1);grid(''on''); ylabel(''Membrane potential (V)'');title(''Preview Data '');'...
'path=''C:\AcqData\Data'';foldername=get(hedit3,''String'');'...
'folder=[path ''\'' foldername];'...
'if exist(folder,''dir'')==0,mkdir(folder);end;'...
'list=dir(fullfile(folder));[r,c]=size(list);r=round(r/2);'...
'if(get(hcheck4,''Value'')==get(hcheck4,''Max'')),r=r-1;end;'...
'if r<10,filename1=sprintf([foldernamenum2str(r,''00%d.txt'')]);'...
'filename2=sprintf([foldernamenum2str(r,''00%d.mat'')]);'...
'elseif r<100,filename1=sprintf([foldernamenum2str(r,''0%d.txt'')]);'...
'filename2=sprintf([foldernamenum2str(r,''0%d.mat'')]);'...
'else, filename1=sprintf([foldernamenum2str(r,''%d.txt'')]);'...
'filename2=sprintf([foldernamenum2str(r,''%d.mat'')]);end;'...
'fullfilename1=fullfile(folder,filename1);fullfilename2=fullfile(folder,filename2);'...
'acq_t=get(hedit2,''String'');'...
'save(fullfilename2,''Y1'',''Y2'',''Y3'',''acq_t'',''YY1'',''YY2'',''time1'',''N'');'...
'fid=fopen(fullfilename1,''w'');'...
'fprintf(fid,''%s\r\n'',''nombresimages:'',(get(hedit1,''String'')));'...
'fprintf(fid,''%s\r\n'',''acquisitiont:'',(get(hedit2,''String'')));'...
'fprintf(fid,''%s\r\n'',''Commentaires:'',com);fclose(fid);'...
'savedfile=[''Lastsavedfile:'' filename2];set(htext4,''string'',savedfile);'...
'if (get(hcheck4,''Value'')==get(hcheck4,''Max'')),'...
'set(hcheck4,''Value'',0);end;'...
'[filenam,pathnam]=[filename,path];'...
'loadedfile=[''Loaded file:'' filenam];'...
'set(htext5,''string'',filenam);'...
'set(hedit1l,''string'',acq_t);'...
'set(hedit2l,''string'',N);'...
'set(hedit3l,''string'',filenam(1:end-4));']);

uicontrol(f,'Style','push','Units','normalized',...
 'String','Load','Position',[0.6 0.01 0.1 0.04],...
'Callback',['[filenam,pathnam]=uigetfile();'...
'loadedfile=[''Loaded file:'' filenam];'...
'set(htext5,''string'',filenam);'...
'S=load([pathnam ''\'' filenam]);'...
'if fr_hold==1, hold on; else,hold off;end;'...
'figure(1);subplot(''Position'',[0.1 0.3 0.85 0.3]);plot(S.time1,S.Y2);grid(''on'');ylabel(''membrane current (A)'');xlabel(''time'');'...
'figure(1);subplot(''Position'',[0.1 0.65 0.85 0.3]);plot(S.time1,S.Y1);grid(''on''); ylabel(''Membrane potential (V)'');title(''Preview Data'');'...
'set(hedit1l,''string'',S.acq_t);'...
'set(hedit2l,''string'',S.N);'...
'set(hedit3l,''string'',filenam(1:end-4));']);


uicontrol(f,'Style','push','Units','normalized',...
 'String','Next','Position',[0.85 0.01 0.1 0.04],...
  'Callback',['if str2num(filenam(end-5:end-4))<100,',...
 'w1=str2num(filenam(end-5:end-4))+1;,',...
 'if w1<10,v1=[''0'',num2str(w1)];',...
 'else,v1=num2str(w1);end,',...
'filenam(end-5:end-4)=v1;end,set(htext5,''string'',filenam);',...
 'S=load([pathnam ''\'' filenam]);'...
 'if fr_hold==1, hold on; else,hold off;end;'...
'figure(1);subplot(''Position'',[0.1 0.3 0.85 0.3]);plot(S.time1,S.Y2);grid(''on'');ylabel(''membrane current (A)'');xlabel(''time'');'...
'figure(1);subplot(''Position'',[0.1 0.65 0.85 0.3]);plot(S.time1,S.Y1);grid(''on''); ylabel(''Membrane potential (V)'');title(''Preview Data'');'...
'set(hedit1l,''string'',S.acq_t);'...
'set(hedit2l,''string'',S.N);'...
'set(hedit3l,''string'',filenam(1:end-4));']);

uicontrol(f,'Style','push','Units','normalized',...
 'String','Previous','Position',[0.73 0.01 0.1 0.04],...
  'Callback',[' if str2num(filenam(end-5:end-4))>1,',...
'w1=str2num(filenam(end-5:end-4))-1;,',...
'if w1<10,v1=[''0'',num2str(w1)];',...
'else,v1=num2str(w1);end,',...
'filenam(end-5:end-4)=v1;end,set(htext5,''string'',filenam);',...
 'S=load([pathnam ''\'' filenam]);'...
 'if fr_hold==1, hold on; else,hold off;end;'...
'figure(1);subplot(''Position'',[0.1 0.3 0.85 0.3]);plot(S.time1,S.Y2);grid(''on'');ylabel(''membrane current (A)'');xlabel(''time'');'...
'figure(1);subplot(''Position'',[0.1 0.65 0.85 0.3]);plot(S.time1,S.Y1);grid(''on''); ylabel(''Membrane potential (V)'');title(''Preview Data'');'...
'set(hedit1l,''string'',S.acq_t);'...
'set(hedit2l,''string'',S.N);'...
'set(hedit3l,''string'',filenam(1:end-4));']);


 z_hold=uicontrol('Style', 'checkbox','Units','normalized','FontSize',8,...
     'Position', [0.85 0.2 0.1 0.04],'String', 'hold',...
     'Callback',['fr_hold=get(z_hold,''Value'');']);