f = figure(1);
set(f,'Position',[100 500 800 300]);
AX=axes; set (AX,'Position',[0.05 0.08 0.55 0.62]);
AX1=axes; set (AX1,'Position',[0.05 0.74 0.4 0.24]); axis off;
l1=line([0 0],[0 0]); l2=line([0 0],[0 0]);

t=(1:800)/100; dl1=0; dl2=0; dl3=0; tpr=20;
NpointsW=24; WIN1=round(NpointsW/3); WIN2=NpointsW-WIN1;

uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.65 0.02 0.1 0.08],...
    'String','load file',...
    'FontSize',11,...
    'Callback',['[file perc]=uigetfile(''*.mat'',''load data file'');,',...
    'eval([''load '',file]);,',...
    'axes(AX1); imshow(avg,[min(min(avg)) max(max(avg))]);,',...
    'l1=line([Pos1 Pos1],[2 28]);,',...
    'l2=line([Pos2 Pos2],[2 28]);,',...
    'set(txtfile,''String'',[file]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.76 0.02 0.06 0.08],...
    'String','other',...
    'FontSize',11,...
    'Callback',['axes(AX1); imshow(avgb,[min(min(avg)) max(max(avgb))]);,',...
    'l1=line([Pos1 Pos1],[2 28]);,',...
    'l2=line([Pos2 Pos2],[2 28]);,',...
    'set(txtfile,''String'',[file]);']);
txtfile=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.83 0.02 0.15 0.08],...
    'String','file ---',...
    'FontSize',11);

dlpk_text=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.45 0.92 0.15 0.06],...
    'String',['delay peak: ','---'],...
    'FontSize',10);
dif_text=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.45 0.86 0.15 0.06],...
    'String',['dif curve: ','---'],...
    'FontSize',10);
wid1_text=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.45 0.8 0.15 0.06],...
    'String',['width 1:  ','---'],...
    'FontSize',10);
wid2_text=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.45 0.74 0.15 0.06],...
    'String',['width 2:  ','---'],...
    'FontSize',10);

Pos1=35;
uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.65 0.9 0.1 0.08],...
    'String','position 1',...
    'FontSize',11);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.76 0.9 0.04 0.08],...
    'String','+',...
    'FontSize',11,...
    'Callback',['Pos1=Pos1+1;,',...
    'delete(l1); delete(l2);,',...
    'axes(AX1); l1=line([Pos1 Pos1],[2 28]); l2=line([Pos2 Pos2],[2 28]);,',...
    'set(txtpos,''String'',num2str(Pos1));']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.81 0.9 0.04 0.08],...
    'String','-',...
    'FontSize',11,...
    'Callback',['Pos1=Pos1-1;,',...
    'delete(l1); delete(l2);,',...
    'axes(AX1); l1=line([Pos1 Pos1],[2 28]); l2=line([Pos2 Pos2],[2 28]);,',...
    'set(txtpos,''String'',num2str(Pos1));']);
txtpos=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.86 0.9 0.04 0.08],...
    'String','35',...
    'FontSize',11);

Pos2=80;
uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.65 0.8 0.1 0.08],...
    'String','position 2',...
    'FontSize',11);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.76 0.8 0.04 0.08],...
    'String','+',...
    'FontSize',11,...
    'Callback',['Pos2=Pos2+1;,',...
    'delete(l1); delete(l2);,',...
    'axes(AX1); l1=line([Pos1 Pos1],[2 28]); l2=line([Pos2 Pos2],[2 28]);,',...
    'set(txtwid,''String'',num2str(Pos2));']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.81 0.8 0.04 0.08],...
    'String','-',...
    'FontSize',11,...
    'Callback',['Pos2=Pos2-1;,',...
    'delete(l1); delete(l2);,',...
    'axes(AX1); l1=line([Pos1 Pos1],[2 28]); l2=line([Pos2 Pos2],[2 28]);,',...
    'set(txtwid,''String'',num2str(Pos2));']);
txtwid=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.86 0.8 0.04 0.08],...
    'String','80',...
    'FontSize',11);

uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.91 0.9 0.08 0.08],...
    'String','plot 1',...
    'FontSize',11,...
    'Callback',['vmc=linesignal(Pos1,:); vmd=linesignalb(Pos1,:);,',...
    'axes(AX);,',...
    'plot([vmc'' vmd'']);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.91 0.8 0.08 0.08],...
    'String','plot 2',...
    'FontSize',11,...
    'Callback',['vmc2=linesignal(Pos2,:); vmd2=linesignalb(Pos2,:);,',...
    'axes(AX);,',...
    'plot([vmc2'' vmd2'']);']);

uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.65 0.68 0.14 0.08],...
    'String','superimpose 1',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb; dl1=0; massc1=find(apc==max(apc)); massd1=find(apd==max(apd));,',...
    'massc=find(vmc==max(vmc)); massd=massc+round((massd1-massc1)/2);,',...
    'vvmc=vmc(massc-WIN1:massc+WIN2);,',...
    'vvmd=vmd(massd-WIN1+dl1:massd+WIN2+dl1);,',...
    'set(psb1,''Visible'',''on'');',...
    'set(psb2,''Visible'',''on'');',...
    'delPK=find(vvmd==max(vvmd))-find(vvmc==max(vvmc));,',...
    'set(dlpk_text,''String'',[''delay peak: '',num2str(delPK)]);,',...
    'set(wid1_text,''String'',[''width 1:  '',num2str(length(find(vvmc>(max(vvmc)/2+mean(vvmc(1:3))))))]);,',...
    'set(wid2_text,''String'',[''width 2:  '',num2str(length(find(vvmd>(max(vvmd)/2+mean(vvmd(1:3))))))]);,',...
    'axes(AX);,',...
    'plot([vvmc'' vvmd'' ones(length(vvmc),1)*(max(vvmc)/2+mean(vvmc(1:3)))]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.8 0.68 0.03 0.08],...
    'String','+',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb; dl1=dl1+1; massc1=find(apc==max(apc)); massd1=find(apd==max(apd));,',...
    'massc=find(vmc==max(vmc)); massd=massc+round((massd1-massc1)/2);,',...
    'vvmc=vmc(massc-WIN1:massc+WIN2);,',...
    'vvmd=vmd(massd-WIN1+dl1:massd+WIN2+dl1);,',...
    'delPK=find(vvmd==max(vvmd))-find(vvmc==max(vvmc));,',...
    'set(dlpk_text,''String'',[''delay peak: '',num2str(delPK)]);,',...
    'set(wid1_text,''String'',[''width 1:  '',num2str(length(find(vvmc>(max(vvmc)/2+mean(vvmc(1:3))))))]);,',...
    'set(wid2_text,''String'',[''width 2:  '',num2str(length(find(vvmd>(max(vvmd)/2+mean(vvmd(1:3))))))]);,',...
    'axes(AX);,',...
    'plot([vvmc'' vvmd'' ones(length(vvmc),1)*(max(vvmc)/2+mean(vvmc(1:3)))]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.83 0.68 0.03 0.08],...
    'String','-',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb; dl1=dl1-1; massc1=find(apc==max(apc)); massd1=find(apd==max(apd));,',...
    'massc=find(vmc==max(vmc)); massd=massc+round((massd1-massc1)/2);,',...
    'vvmc=vmc(massc-WIN1:massc+WIN2);,',...
    'vvmd=vmd(massd-WIN1+dl1:massd+WIN2+dl1);,',...
    'delPK=find(vvmd==max(vvmd))-find(vvmc==max(vvmc));,',...
    'set(dlpk_text,''String'',[''delay peak: '',num2str(delPK)]);,',...
    'set(wid1_text,''String'',[''width 1:  '',num2str(length(find(vvmc>(max(vvmc)/2+mean(vvmc(1:3))))))]);,',...
    'set(wid2_text,''String'',[''width 2:  '',num2str(length(find(vvmd>(max(vvmd)/2+mean(vvmd(1:3))))))]);,',...
    'axes(AX);,',...
    'plot([vvmc'' vvmd'' ones(length(vvmc),1)*(max(vvmc)/2+mean(vvmc(1:3)))]);']);
WINDO=uicontrol('Style','Edit',...
    'Units','normalized',...
    'Position',[0.8 0.58 0.04 0.08],...
    'String','2.4',...
    'FontSize',11,...
    'Callback',['NpointsW=round(10*str2num(get(WINDO,''String'')));,',...
    'WIN1=round(NpointsW/3); WIN2=NpointsW-WIN1;']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.9 0.68 0.08 0.08],...
    'String','differ 1',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb; massc1=find(apc==max(apc)); massd1=find(apd==max(apd));,',...
    'massc=find(vmc==max(vmc)); massd=massc+round((massd1-massc1)/2);,',...
    'vvmc=vmc(massc-WIN1:massc+WIN2);,',...
    'vvmd=vmd(massd-WIN1+dl1:massd+WIN2+dl1);,',...
    'integrDIF=100*cumsum(vvmc-vvmd)/cumsum(vvmc);,',...
    'set(dif_text,''String'',[''dif curve: '',num2str(integrDIF(end))]);,',...
    'axes(AX);,',...
    'plot([cumsum(vvmc)''/NpointsW cumsum(vvmd)''/NpointsW cumsum(vvmc-vvmd)''/NpointsW]);']);


psb1=uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.65 0.58 0.14 0.08],...
    'String','superimpose 2',...
    'FontSize',11,...
    'Visible','off',...
    'Callback',['vvmc2=vmc2(massc-WIN1:massc+WIN2);,',...
    'vvmd2=vmd2(massd-WIN1+dl1:massd+WIN2+dl1);,',...
    'delPK2=find(vvmd2==max(vvmd2))-find(vvmc2==max(vvmc2));,',...
    'set(dlpk_text,''String'',[''delay peak: '',num2str(delPK2)]);,',...
    'set(wid1_text,''String'',[''width 1:  '',num2str(length(find(vvmc2>(max(vvmc2)/2+mean(vvmc2(1:3))))))]);,',...
    'set(wid2_text,''String'',[''width 2:  '',num2str(length(find(vvmd2>(max(vvmd2)/2+mean(vvmd2(1:3))))))]);,',...
    'axes(AX);,',...
    'plot([vvmc2'' vvmd2'' ones(length(vvmc2),1)*(max(vvmc2)/2+mean(vvmc2(1:3)))]);']);
psb2=uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.9 0.58 0.08 0.08],...
    'String','differ 2',...
    'FontSize',11,...
    'Visible','off',...
    'Callback',['vvmc2=vmc2(massc-WIN1:massc+WIN2);,',...
    'vvmd2=vmd2(massd-WIN1+dl1:massd+WIN2+dl1);,',...
    'integrDIF2=100*cumsum(vvmc2-vvmd2)/cumsum(vvmc2);,',...
    'set(dif_text,''String'',[''dif curve '',num2str(integrDIF2(end))]);,',...
    'axes(AX);,',...
    'plot([cumsum(vvmc2)''/NpointsW cumsum(vvmd2)''/NpointsW cumsum(vvmc2-vvmd2)''/NpointsW]);']);


% SOMA-------------------------------------------
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.86 0.12 0.12 0.08],...
    'String','soma both',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb;,',...
    'axes(AX);,',...
    'plot([apc apd]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.65 0.12 0.12 0.08],...
    'String','soma sup',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb; dl3=0; massc1=find(apc==max(apc)); massd1=find(apd==max(apd));,',...
    'apc1=apc(massc1-2*WIN1:massc1+2*WIN2);,',...
    'apd1=apd(massd1-2*WIN1+dl3:massd1+2*WIN2+dl3);,',...
    'axes(AX);,',...
    'plot([apc1 apd1]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.78 0.12 0.03 0.08],...
    'String','+',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb; dl3=dl3+1; massc1=find(apc==max(apc)); massd1=find(apd==max(apd));,',...
    'apc1=apc(massc1-2*WIN1:massc1+2*WIN2);,',...
    'apd1=apd(massd1-2*WIN1+dl3:massd1+2*WIN2+dl3);,',...
    'axes(AX);,',...
    'plot([apc1 apd1]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.81 0.12 0.03 0.08],...
    'String','-',...
    'FontSize',11,...
    'Callback',['apc=Vm; apd=Vmb; dl3=dl3-1; massc1=find(apc==max(apc)); massd1=find(apd==max(apd));,',...
    'apc1=apc(massc1-2*WIN1:massc1+2*WIN2);,',...
    'apd1=apd(massd1-2*WIN1+dl3:massd1+2*WIN2+dl3);,',...
    'axes(AX);,',...
    'plot([apc1 apd1]);']);
%-----------------------------------------------------

uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.65 0.35 0.09 0.08],...
    'String','control 1',...
    'FontSize',11,...
    'Callback',['massc=find(vmc==max(vmc)); massd=find(vmd==max(vmd));,',...
    'vvmc=vmc(massc-WIN1:massc+WIN2);,',...
    'vvmd=vmd(massd-WIN1:massd+WIN2);,',...
    'aapc=(apc(1:2:end)''+apc(2:2:end)'')/2; aapc1=aapc(massc-WIN1+3:massc+WIN2+3);',...
    'aapd=(apd(1:2:end)''+apd(2:2:end)'')/2; aapd1=aapd(massd-WIN1+3:massd+WIN2+3);',...
    'xdata=1:length(aapc1); f1 = @(x1,xdata)x1(1)*aapc1+x1(2); f2 = @(x2,xdata)x2(1)*aapd1+x2(2);,',...
    'x1 = lsqcurvefit(f1,[0.01 0],xdata,vvmc);,',...
    'axes(AX);,',...
    'plot([vvmc'' x1(1)*aapc1''+x1(2)]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.75 0.35 0.09 0.08],...
    'String','drug 1',...
    'FontSize',11,...
    'Callback',['massc=find(vmc==max(vmc)); massd=find(vmd==max(vmd));,',...
    'vvmc=vmc(massc-WIN1:massc+WIN2);,',...
    'vvmd=vmd(massd-WIN1:massd+WIN2);,',...
    'aapc=(apc(1:2:end)''+apc(2:2:end)'')/2; aapc1=aapc(massc-WIN1+3:massc+WIN2+3);',...
    'aapd=(apd(1:2:end)''+apd(2:2:end)'')/2; aapd1=aapd(massd-WIN1+3:massd+WIN2+3);',...
    'xdata=1:length(aapc1); f1 = @(x1,xdata)x1(1)*aapc1+x1(2); f2 = @(x2,xdata)x2(1)*aapd1+x2(2);,',...
    'x2 = lsqcurvefit(f2,[0.01 0],xdata,vvmd);,',...
    'axes(AX);,',...
    'plot([vvmd'' x2(1)*aapd1''+x2(2)]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.85 0.35 0.09 0.08],...
    'String','differAP 1',...
    'FontSize',11,...
    'Callback',['massc=find(vmc==max(vmc)); massd=find(vmd==max(vmd));,',...
    'vvmc=vmc(massc-WIN1:massc+WIN2);,',...
    'vvmd=vmd(massd-WIN1:massd+WIN2);,',...
    'aapc=(apc(1:2:end)''+apc(2:2:end)'')/2; aapc1=aapc(massc-WIN1+3:massc+WIN2+3);',...
    'aapd=(apd(1:2:end)''+apd(2:2:end)'')/2; aapd1=aapd(massd-WIN1+3:massd+WIN2+3);',...
    'xdata=1:length(aapc1); f1 = @(x1,xdata)x1(1)*aapc1+x1(2); f2 = @(x2,xdata)x2(1)*aapd1+x2(2);,',...
    'x1 = lsqcurvefit(f1,[0.01 0],xdata,vvmc);,',...
    'x2 = lsqcurvefit(f2,[0.01 0],xdata,vvmd);,',...
    'axes(AX);,',...
    'plot([cumsum(vvmc)''-cumsum(x1(1)*aapc1+x1(2))'' cumsum(vvmd)''-cumsum(x2(1)*aapd1+x2(2))'']);']);

uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.65 0.25 0.09 0.08],...
    'String','control 2',...
    'FontSize',11,...
    'Callback',['massc2=find(vmc2==max(vmc2)); massd2=find(vmd2==max(vmd2));,',...
    'vvmc2=vmc2(massc2-WIN1:massc2+WIN2);,',...
    'vvmd2=vmd2(massd2-WIN1:massd2+WIN2);,',...
    'aapc=(apc(1:2:end)''+apc(2:2:end)'')/2; aapc2=aapc(massc2-WIN1+3:massc2+WIN2+3);',...
    'aapd=(apd(1:2:end)''+apd(2:2:end)'')/2; aapd2=aapd(massd2-WIN1+3:massd2+WIN2+3);',...
    'xdata=1:length(aapc2); f1 = @(x1,xdata)x1(1)*aapc2+x1(2); f2 = @(x2,xdata)x2(1)*aapd2+x2(2);,',...
    'x1 = lsqcurvefit(f1,[0.01 0],xdata,vvmc2);,',...
    'axes(AX);,',...
    'plot([vvmc2'' x1(1)*aapc2''+x1(2)]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.75 0.25 0.09 0.08],...
    'String','drug 2',...
    'FontSize',11,...
    'Callback',['massc2=find(vmc2==max(vmc2)); massd2=find(vmd2==max(vmd2));,',...
    'vvmc2=vmc2(massc2-WIN1:massc2+WIN2);,',...
    'vvmd2=vmd2(massd2-WIN1:massd2+WIN2);,',...
    'aapc=(apc(1:2:end)''+apc(2:2:end)'')/2; aapc2=aapc(massc2-WIN1+3:massc2+WIN2+3);',...
    'aapd=(apd(1:2:end)''+apd(2:2:end)'')/2; aapd2=aapd(massd2-WIN1+3:massd2+WIN2+3);',...
    'xdata=1:length(aapc2); f1 = @(x1,xdata)x1(1)*aapc2+x1(2); f2 = @(x2,xdata)x2(1)*aapd2+x2(2);,',...
    'x2 = lsqcurvefit(f2,[0.01 0],xdata,vvmd2);,',...
    'axes(AX);,',...
    'plot([vvmd2'' x2(1)*aapd2''+x2(2)]);']);
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.85 0.25 0.09 0.08],...
    'String','differAP 2',...
    'FontSize',11,...
    'Callback',['massc2=find(vmc2==max(vmc2)); massd2=find(vmd2==max(vmd2));,',...
    'vvmc2=vmc2(massc2-WIN1:massc2+WIN2);,',...
    'vvmd2=vmd2(massd2-WIN1:massd2+WIN2);,',...
    'aapc=(apc(1:2:end)''+apc(2:2:end)'')/2; aapc2=aapc(massc2-WIN1+3:massc2+WIN2+3);',...
    'aapd=(apd(1:2:end)''+apd(2:2:end)'')/2; aapd2=aapd(massd2-WIN1+3:massd2+WIN2+3);',...
    'xdata=1:length(aapc2); f1 = @(x1,xdata)x1(1)*aapc2+x1(2); f2 = @(x2,xdata)x2(1)*aapd2+x2(2);,',...
    'x1 = lsqcurvefit(f1,[0.01 0],xdata,vvmc2);,',...
    'x2 = lsqcurvefit(f2,[0.01 0],xdata,vvmd2);,',...
    'axes(AX);,',...
    'plot([cumsum(vvmc2)''-cumsum(x1(1)*aapc2+x1(2))'' cumsum(vvmd2)''-cumsum(x2(1)*aapd2+x2(2))'']);']);