f=figure(1); set(f,'Position',[50 200 600 400],'Name','Dual camera analysis','Menubar','none');
AX1b=axes; set(AX1b,'Position',[0.32 0.44 0.6 0.45]); axis off;
radio_bl=0;
radio_fl=0;
xAP=[];
yAP=[];
lab1=0;
lab2=0;
REVERS=-10;
RMP=-64;
II1=[]; II2=[]; II3=[]; II4=[];
II1b=[]; II2b=[]; II3b=[]; II4b=[];

% Loading file section
uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.01 0.12 0.05],...
    'String','load file',...
    'FontSize',11,...
    'Callback',['[file perc]=uigetfile(''*.mat'',''load data file'');,',...
    'eval([''load '',file]);,',...
    'SX=size(Y,1)/2; SY=size(Y,2)/4;,',...
    'Ya=Y(:,1:2*SY,:); Yb=Y(:,2*SY+1:4*SY,:);,',... 
    'BKmin1=min(min(mean(Yb(1:2,1:13,:),3))); Yb(1:2,1:13,1:size(Yb,3))=Yb(1:2,1:13,1:size(Yb,3))-BKmin1;,',...
    'BKmin2=min(min(mean(Yb(3:4,1:13,:),3))); Yb(3:4,1:13,1:size(Yb,3))=Yb(3:4,1:13,1:size(Yb,3))-BKmin2;,',...
    'BKmin3=min(min(mean(Yb(1:2,14:26,:),3))); Yb(1:2,14:26,1:size(Yb,3))=Yb(1:2,14:26,1:size(Yb,3))-BKmin3;,',...
    'BKmin4=min(min(mean(Yb(3:4,14:26,:),3))); Yb(3:4,14:26,1:size(Yb,3))=Yb(3:4,14:26,1:size(Yb,3))-BKmin4;,',...
    'Mb=mean(Yb,3);,',...
    'axes(AX1b);,',...
    'imshow(Mb,[min(min(Mb)) max(max(Mb))]);,',...
    'MP=mean(y(51:100));,',...
    'set(prev,''Visible'',''on'');,',...
    'set(succ,''Visible'',''on'');,',...
    'set(txtfile,''String'',file(end-6:end-4));,',...
    'radio_fl=1;,',...
    'II1=zeros(size(Y,3),1);,',...
    'II2=zeros(size(Y,3),1);,',...
    'II3=zeros(size(Y,3),1);,',...
    'II4=zeros(size(Y,3),1);,',...
    'II1b=zeros(size(Y,3),1);,',...
    'II2b=zeros(size(Y,3),1);,',...
    'II3b=zeros(size(Y,3),1);,',...
    'II4b=zeros(size(Y,3),1);,',...
    'axes(AX1b);,',...
    'lb=line([1,2,2,1,1],[1,1,2,2,1]);']);
txtfile=uicontrol('Style','Text',...
    'Units','normalized',...
    'Position',[0.17 0.01 0.1 0.05],...
    'String','file ---',...
    'FontSize',11);
prev=uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.30 0.01 0.12 0.05],...
    'Visible','off',...
    'String','previous',...
    'FontSize',11,...
    'Callback',['if str2num(file(end-5:end-4))>1,',...
    'presnum=str2num(file(end-5:end-4))-1;,',...
    'if presnum<10,',...
    'finalFL=[''0'',num2str(presnum)];,',...
    'else,',...
    'finalFL=num2str(presnum);,',...
    'end,',...
    'file(end-5:end-4)=finalFL;,',...
    'end,',...
    'eval([''load '',file]);,',...
    'SX=size(Y,1)/2; SY=size(Y,2)/4;,',...
    'Ya=Y(:,1:2*SY,:); Yb=Y(:,2*SY+1:4*SY,:);,',... 
    'BKmin1=min(min(mean(Yb(1:2,1:13,:),3))); Yb(1:2,1:13,1:size(Yb,3))=Yb(1:2,1:13,1:size(Yb,3))-BKmin1;,',...
    'BKmin2=min(min(mean(Yb(3:4,1:13,:),3))); Yb(3:4,1:13,1:size(Yb,3))=Yb(3:4,1:13,1:size(Yb,3))-BKmin2;,',...
    'BKmin3=min(min(mean(Yb(1:2,14:26,:),3))); Yb(1:2,14:26,1:size(Yb,3))=Yb(1:2,14:26,1:size(Yb,3))-BKmin3;,',...
    'BKmin4=min(min(mean(Yb(3:4,14:26,:),3))); Yb(3:4,14:26,1:size(Yb,3))=Yb(3:4,14:26,1:size(Yb,3))-BKmin4;,',...
    'Mb=mean(Yb,3);,',...
    'axes(AX1b);,',...
    'imshow(Mb,[min(min(Mb)) max(max(Mb))]);,',...
    'MP=mean(y(51:100));,',...
    'set(prev,''Visible'',''on'');,',...
    'set(succ,''Visible'',''on'');,',...
    'set(txtfile,''String'',file(end-6:end-4));,',...
    'radio_fl=1;,',...
    'II1=zeros(size(Y,3),1);,',...
    'II2=zeros(size(Y,3),1);,',...
    'II3=zeros(size(Y,3),1);,',...
    'II4=zeros(size(Y,3),1);,',...
    'II1b=zeros(size(Y,3),1);,',...
    'II2b=zeros(size(Y,3),1);,',...
    'II3b=zeros(size(Y,3),1);,',...
    'II4b=zeros(size(Y,3),1);,',...
    'axes(AX1b);,',...
    'lb=line([1,2,2,1,1],[1,1,2,2,1]);']);
succ=uicontrol('Style','Pushbutton',...
    'Units','normalized',...
    'Position',[0.44 0.01 0.06 0.05],...
    'Visible','off',...
    'String','next',...
    'FontSize',11,...
    'Callback',['if str2num(file(end-5:end-4))<99,',...
    'presnum=str2num(file(end-5:end-4))+1;,',...
    'if presnum<10,',...
    'finalFL=[''0'',num2str(presnum)];,',...
    'else,',...
    'finalFL=num2str(presnum);,',...
    'end,',...
    'file(end-5:end-4)=finalFL;,',...
    'end,',...
    'eval([''load '',file]);,',...
    'SX=size(Y,1)/2; SY=size(Y,2)/4;,',...
    'Ya=Y(:,1:2*SY,:); Yb=Y(:,2*SY+1:4*SY,:);,',... 
    'BKmin1=min(min(mean(Yb(1:2,1:13,:),3))); Yb(1:2,1:13,1:size(Yb,3))=Yb(1:2,1:13,1:size(Yb,3))-BKmin1;,',...
    'BKmin2=min(min(mean(Yb(3:4,1:13,:),3))); Yb(3:4,1:13,1:size(Yb,3))=Yb(3:4,1:13,1:size(Yb,3))-BKmin2;,',...
    'BKmin3=min(min(mean(Yb(1:2,14:26,:),3))); Yb(1:2,14:26,1:size(Yb,3))=Yb(1:2,14:26,1:size(Yb,3))-BKmin3;,',...
    'BKmin4=min(min(mean(Yb(3:4,14:26,:),3))); Yb(3:4,14:26,1:size(Yb,3))=Yb(3:4,14:26,1:size(Yb,3))-BKmin4;,',...
    'Mb=mean(Yb,3);,',...
    'axes(AX1b);,',...
    'imshow(Mb,[min(min(Mb)) max(max(Mb))]);,',...
    'MP=mean(y(51:100));,',...
    'set(prev,''Visible'',''on'');,',...
    'set(succ,''Visible'',''on'');,',...
    'set(txtfile,''String'',file(end-6:end-4));,',...
    'radio_fl=1;,',...
    'II1=zeros(size(Y,3),1);,',...
    'II2=zeros(size(Y,3),1);,',...
    'II3=zeros(size(Y,3),1);,',...
    'II4=zeros(size(Y,3),1);,',...
    'II1b=zeros(size(Y,3),1);,',...
    'II2b=zeros(size(Y,3),1);,',...
    'II3b=zeros(size(Y,3),1);,',...
    'II4b=zeros(size(Y,3),1);,',...
    'axes(AX1b);,',...
    'lb=line([1,2,2,1,1],[1,1,2,2,1]);']);



%Region selection and plot
tr1bx=uicontrol(f,'Style','edit',...
 'String','1','Units','normalized',...
 'Position',[0.08 0.84 0.06 0.04]);
tr1by=uicontrol(f,'Style','edit',...
 'String','1','Units','normalized',...
 'Position',[0.08 0.80 0.06 0.04]);
tr1bdx=uicontrol(f,'Style','edit',...
 'String','5','Units','normalized',...
 'Position',[0.08 0.76 0.06 0.04]);
tr1bdy=uicontrol(f,'Style','edit',...
 'String','4','Units','normalized',...
 'Position',[0.08 0.72 0.06 0.04]);
uicontrol(f,'Style','push',...
 'String','reg 1b','Units','normalized',...
 'Position',[0.08 0.94 0.06 0.04],'Callback',['axes(AX1b); [I1,R]=imcrop;,',...
 'R=round(R);,',...
 'R1=R;,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'set(tr1bx,''String'',num2str(R(1)));,',...
 'set(tr1by,''String'',num2str(R(2)));,',...
 'set(tr1bdx,''String'',num2str(R(3)));,',...
 'set(tr1bdy,''String'',num2str(R(4)));']);
uicontrol(f,'Style','push',...
 'String','show','Units','normalized',...
 'Position',[0.08 0.89 0.06 0.04],'Callback',['R1(1)=str2num(get(tr1bx,''String''));,',...
 'R1(2)=str2num(get(tr1by,''String''));,',...
 'R1(3)=str2num(get(tr1bdx,''String''));,',...
 'R1(4)=str2num(get(tr1bdy,''String''));,',...
 'II1b=zeros(size(Y,3),1);,',...
 'BKR1=mean(mean(imcrop(Yb(:,:,1),R1)));,',...
 'for k=1:length(II1b),',...
 'II1b(k)=mean(mean(imcrop(Yb(:,:,k),R1)));,',...
 'end,',...
 'II1=II1b;,',...
 'II1b=(II1b-mean(II1b(2:7)))/mean(II1b(2:7));,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'R=R1;,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'fpl=figure(3); set(fpl,''Position'',[660 200 400 120]);,',...
 'plot((1:length(II1b))*A(4),II1b);']);
uicontrol(f,'Style','push',...
 'String','raw','Units','normalized',...
 'Position',[0.08 0.66 0.06 0.04],'Callback',['R1(1)=str2num(get(tr1bx,''String''));,',...
 'R1(2)=str2num(get(tr1by,''String''));,',...
 'R1(3)=str2num(get(tr1bdx,''String''));,',...
 'R1(4)=str2num(get(tr1bdy,''String''));,',...
 'II1b=zeros(size(Y,3),1);,',...
 'BKR1=mean(mean(imcrop(Yb(:,:,1),R1)));,',...
 'for k=1:length(II1b),',...
 'II1b(k)=mean(mean(imcrop(Yb(:,:,k),R1)));,',...
 'end,',...
 'ydata=II1b; firpo=mean(ydata(1:4))/3;,',...
 'xdata= (1:length(II1b))''*A(4);,',... 
 'Blc_fun = @(x,xdata)x(1)*exp(xdata*x(2))+ x(3)*exp(xdata*x(4))+x(5)*exp(xdata*x(6));,',...
 'x = lsqcurvefit(Blc_fun,[firpo 0 firpo 0 firpo 0],xdata,ydata);,',...
 'yfit=x(1)*exp(xdata*x(2))+ x(3)*exp(xdata*x(4))+x(5)*exp(xdata*x(6));,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'R=R1;,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'fpl=figure(3); set(fpl,''Position'',[660 200 400 120]);,',...
 'plot((1:length(II1b))*A(4),II1b,(1:length(II1b))*A(4),yfit);']);
uicontrol(f,'Style','push',...
 'String','bl-cor','Units','normalized',...
 'Position',[0.08 0.60 0.06 0.04],'Callback',['R1(1)=str2num(get(tr1bx,''String''));,',...
 'R1(2)=str2num(get(tr1by,''String''));,',...
 'R1(3)=str2num(get(tr1bdx,''String''));,',...
 'R1(4)=str2num(get(tr1bdy,''String''));,',...
 'fattore=str2num(get(fatted,''String''));,',...
 'II1b=zeros(size(Y,3),1);,',...
 'BKR1=mean(mean(imcrop(Yb(:,:,1),R1)));,',...
 'for k=1:length(II1b),',...
 'II1b(k)=mean(mean(imcrop(Yb(:,:,k),R1)));,',...
 'end,',...
 'II1b=II1b+yfit(1)-yfit*fattore;,',...
 'II1=II1b;,',...
 'II1b=(II1b-mean(II1b(2:7)))/mean(II1b(2:7));,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'R=R1;,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'fpl=figure(3); set(fpl,''Position'',[660 200 400 120]);,',...
 'plot((1:length(II1b))*A(4),II1b);']);
fatted=uicontrol(f,'Style','edit',...
 'String','1','Units','normalized',...
 'Position',[0.14 0.60 0.06 0.04]);
tr2bx=uicontrol(f,'Style','edit',...
 'String','9','Units','normalized',...
 'Position',[0.14 0.84 0.06 0.04]);
tr2by=uicontrol(f,'Style','edit',...
 'String','1','Units','normalized',...
 'Position',[0.14 0.80 0.06 0.04]);
tr2bdx=uicontrol(f,'Style','edit',...
 'String','5','Units','normalized',...
 'Position',[0.14 0.76 0.06 0.04]);
tr2bdy=uicontrol(f,'Style','edit',...
 'String','4','Units','normalized',...
 'Position',[0.14 0.72 0.06 0.04]);
uicontrol(f,'Style','push',...
 'String','reg 2b','Units','normalized',...
 'Position',[0.14 0.94 0.06 0.04],'Callback',['axes(AX1b); [I1,R]=imcrop;,',...
 'R=round(R);,',...
 'R2=R;,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'set(tr2bx,''String'',num2str(R(1)));,',...
 'set(tr2by,''String'',num2str(R(2)));,',...
 'set(tr2bdx,''String'',num2str(R(3)));,',...
 'set(tr2bdy,''String'',num2str(R(4)));']);
uicontrol(f,'Style','push',...
 'String','show','Units','normalized',...
 'Position',[0.14 0.89 0.06 0.04],'Callback',['R2(1)=str2num(get(tr2bx,''String''));,',...
 'R2(2)=str2num(get(tr2by,''String''));,',...
 'R2(3)=str2num(get(tr2bdx,''String''));,',...
 'R2(4)=str2num(get(tr2bdy,''String''));,',...
 'II2b=zeros(size(Y,3),1);,',...
 'BKR2=mean(mean(imcrop(Yb(:,:,1),R2)));,',...
 'for k=1:length(II2b),',...
 'II2b(k)=mean(mean(imcrop(Yb(:,:,k),R2)));,',...
 'end,',...
 'II2=II2b;,',...
 'II2b=(II2b-mean(II2b(2:7)))/mean(II2b(2:7)); ,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'R=R2;,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'fpl=figure(3); set(fpl,''Position'',[660 200 400 120]);,',...
 'plot((1:length(II2b))*A(4),II2b);']);
tr3bx=uicontrol(f,'Style','edit',...
 'String','18','Units','normalized',...
 'Position',[0.2 0.84 0.06 0.04]);
tr3by=uicontrol(f,'Style','edit',...
 'String','1','Units','normalized',...
 'Position',[0.2 0.80 0.06 0.04]);
tr3bdx=uicontrol(f,'Style','edit',...
 'String','5','Units','normalized',...
 'Position',[0.2 0.76 0.06 0.04]);
tr3bdy=uicontrol(f,'Style','edit',...
 'String','4','Units','normalized',...
 'Position',[0.2 0.72 0.06 0.04]);
uicontrol(f,'Style','push',...
 'String','reg 3b','Units','normalized',...
 'Position',[0.2 0.94 0.06 0.04],'Callback',['axes(AX1b); [I1,R]=imcrop;,',...
 'R=round(R);,',...
 'R3=R;,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'set(tr3bx,''String'',num2str(R(1)));,',...
 'set(tr3by,''String'',num2str(R(2)));,',...
 'set(tr3bdx,''String'',num2str(R(3)));,',...
 'set(tr3bdy,''String'',num2str(R(4)));']);
uicontrol(f,'Style','push',...
 'String','show','Units','normalized',...
 'Position',[0.2 0.89 0.06 0.04],'Callback',['R3(1)=str2num(get(tr3bx,''String''));,',...
 'R3(2)=str2num(get(tr3by,''String''));,',...
 'R3(3)=str2num(get(tr3bdx,''String''));,',...
 'R3(4)=str2num(get(tr3bdy,''String''));,',...
 'II3b=zeros(size(Y,3),1);,',...
 'BKR3=mean(mean(imcrop(Yb(:,:,1),R3)));,',...
 'for k=1:length(II3b),',...
 'II3b(k)=mean(mean(imcrop(Yb(:,:,k),R3)));,',...
 'end,',...
 'II3=II3b;,',...
 'II3b=(II3b-mean(II3b(2:7)))/mean(II3b(2:7)); ,',...
 'axes(AX1b);,',...
 'delete(lb);,',...
 'R=R3;,',...
 'lb=line([R(1),R(1)+R(3),R(1)+R(3),R(1),R(1)],[R(2),R(2),R(2)+R(4),R(2)+R(4),R(2)]);,',...
 'fpl=figure(3); set(fpl,''Position'',[660 200 400 120]);,',...
 'plot((1:length(II3b))*A(4),II3b);']);
%--------------------------------------------------
uicontrol(f,'Style','push',...
 'String','plot Im','Units','normalized',...
 'Position',[0.55 0.01 0.1 0.05],'Callback',['fplz=figure(4); set(fplz,''Position'',[660 500 400 120]);,',...
 'plot((1:A(1)*A(5))*A(4)/A(5),y);']);
uicontrol(f,'Style','push',...
 'String','plot Vm','Units','normalized',...
 'Position',[0.65 0.01 0.1 0.05],'Callback',['fplz=figure(4); set(fplz,''Position'',[660 500 400 120]);,',...
 'plot((1:A(1)*A(5))*A(4)/A(5),y1);']);
%--------------------------------------------------



%------current analysis-------------------
PROV=uicontrol(f,'Style','text',...
 'String','Ca2+ current analysis','Units','normalized',...
 'BackGroundColor',[0.5 0.5 0.5],...
 'Position',[0.76 0 0.24 0.4]);

uicontrol(f,'Style','push',...
 'String','smooth1','Units','normalized',...
 'Position',[0.77 0.28 0.1 0.04],'Callback',['if get(Smo_menu,''Value'')==1,',...
 'TpFlt=''moving'';,',...
 'elseif get(Smo_menu,''Value'')==2,',...
 'TpFlt=''sgolay'';,',...
 'elseif get(Smo_menu,''Value'')==3,',...
 'TpFlt=''rlowess'';,',...
 'elseif get(Smo_menu,''Value'')==4,',...
 'TpFlt=''rloess'';,',...
 'end,',...
 'II1sm=II1b;,',...
 'for kkk=1:get(SmoFois_menu,''Value''),',...
 'II1sm=smooth(II1sm,str2num(get(Smo_val,''String'')),TpFlt);,',...
 'end,',...
 'fpla=figure(2); set(fpla,''Position'',[660 350 400 120],''Menubar'',''none'');,',...
 'plot((1:length(II1b))*A(4),II1b,(1:length(II1b))*A(4),II1sm);']);
uicontrol(f,'Style','push',...
 'String','ICa1','Units','normalized',...
 'Position',[0.89 0.28 0.1 0.04],'Callback',['if get(Smo_menu,''Value'')==1,',...
 'TpFlt=''moving'';,',...
 'elseif get(Smo_menu,''Value'')==2,',...
 'TpFlt=''sgolay'';,',...
 'elseif get(Smo_menu,''Value'')==3,',...
 'TpFlt=''rlowess'';,',...
 'elseif get(Smo_menu,''Value'')==4,',...
 'TpFlt=''rloess'';,',...
 'end,',...
 'II1sm=II1b;,',...
'for kkk=1:get(SmoFois_menu,''Value''),',...
 'II1sm=smooth(II1sm,str2num(get(Smo_val,''String'')),TpFlt);,',...
 'end,',...
 'ICA1=100*40*1.9297*(II1sm(2:end)-II1sm(1:end-1));,',...
 'fpla=figure(2); set(fpla,''Position'',[660 350 400 120],''Menubar'',''none'');,',...
 'plot((1:length(II1b)-1)*A(4),ICA1);']);
uicontrol(f,'Style','push',...
 'String','smooth2','Units','normalized',...
 'Position',[0.77 0.22 0.1 0.04],'Callback',['if get(Smo_menu,''Value'')==1,',...
 'TpFlt=''moving'';,',...
 'elseif get(Smo_menu,''Value'')==2,',...
 'TpFlt=''sgolay'';,',...
 'elseif get(Smo_menu,''Value'')==3,',...
 'TpFlt=''rlowess'';,',...
 'elseif get(Smo_menu,''Value'')==4,',...
 'TpFlt=''rloess'';,',...
 'end,',...
 'II2sm=II2b;,',...
 'for kkk=1:get(SmoFois_menu,''Value''),',...
 'II2sm=smooth(II2sm,str2num(get(Smo_val,''String'')),TpFlt);,',...
 'end,',...
 'fpla=figure(2); set(fpla,''Position'',[660 350 400 120],''Menubar'',''none'');,',...
 'plot((1:length(II2b))*A(4),II2b,(1:length(II2b))*A(4),II2sm);']);
uicontrol(f,'Style','push',...
 'String','ICa2','Units','normalized',...
 'Position',[0.89 0.22 0.1 0.04],'Callback',['if get(Smo_menu,''Value'')==1,',...
 'TpFlt=''moving'';,',...
 'elseif get(Smo_menu,''Value'')==2,',...
 'TpFlt=''sgolay'';,',...
 'elseif get(Smo_menu,''Value'')==3,',...
 'TpFlt=''rlowess'';,',...
 'elseif get(Smo_menu,''Value'')==4,',...
 'TpFlt=''rloess'';,',...
 'end,',...
 'II2sm=II2b;,',...
 'for kkk=1:get(SmoFois_menu,''Value''),',...
 'II2sm=smooth(II2sm,str2num(get(Smo_val,''String'')),TpFlt);,',...
 'end,',...
 'ICA2=100*40*1.9297*(II2sm(2:end)-II2sm(1:end-1));,',...
 'fpla=figure(2); set(fpla,''Position'',[660 350 400 120],''Menubar'',''none'');,',...
 'plot((1:length(II2b)-1)*A(4),ICA2);']);
uicontrol(f,'Style','push',...
 'String','smooth3','Units','normalized',...
 'Position',[0.77 0.16 0.1 0.04],'Callback',['if get(Smo_menu,''Value'')==1,',...
 'TpFlt=''moving'';,',...
 'elseif get(Smo_menu,''Value'')==2,',...
 'TpFlt=''sgolay'';,',...
 'elseif get(Smo_menu,''Value'')==3,',...
 'TpFlt=''rlowess'';,',...
 'elseif get(Smo_menu,''Value'')==4,',...
 'TpFlt=''rloess'';,',...
 'end,',...
 'II3sm=II3b;,',...
'for kkk=1:get(SmoFois_menu,''Value''),',...
 'II3sm=smooth(II3sm,str2num(get(Smo_val,''String'')),TpFlt);,',...
 'end,',...
 'fpla=figure(2); set(fpla,''Position'',[660 350 400 120],''Menubar'',''none'');,',...
 'plot((1:length(II3b))*A(4),II3b,(1:length(II3b))*A(4),II3sm);']);
uicontrol(f,'Style','push',...
 'String','ICa3','Units','normalized',...
 'Position',[0.89 0.16 0.1 0.04],'Callback',['if get(Smo_menu,''Value'')==1,',...
 'TpFlt=''moving'';,',...
 'elseif get(Smo_menu,''Value'')==2,',...
 'TpFlt=''sgolay'';,',...
 'elseif get(Smo_menu,''Value'')==3,',...
 'TpFlt=''rlowess'';,',...
 'elseif get(Smo_menu,''Value'')==4,',...
 'TpFlt=''rloess'';,',...
 'end,',...
 'II3sm=II3b;,',...
 'for kkk=1:get(SmoFois_menu,''Value''),',...
 'II3sm=smooth(II3sm,str2num(get(Smo_val,''String'')),TpFlt);,',...
 'end,',...
 'ICA3=100*40*1.9297*(II3sm(2:end)-II3sm(1:end-1));,',...
 'fpla=figure(2); set(fpla,''Position'',[660 350 400 120],''Menubar'',''none'');,',...
 'plot((1:length(II3b)-1)*A(4),ICA3);']);

Smo_menu=uicontrol(f,'Style','popup',...
 'BackGroundColor',[0.9 0.9 0.9],...
 'Fontsize',7,...
 'Units','normalized',...
 'Position',[0.77 0.08 0.12 0.04],...
 'Value',2,...
 'String','moving|sgolay|rlowess|rloess');

Smo_val=uicontrol(f,'Style','edit',...
 'BackGroundColor',[0.9 0.9 0.9],...
 'Fontsize',7,...
 'Units','normalized',...
 'Position',[0.9 0.08 0.09 0.04],...
 'String','20');
SmoFois_menu=uicontrol(f,'Style','popup',...
 'BackGroundColor',[0.9 0.9 0.9],...
 'Fontsize',7,...
 'Units','normalized',...
 'Position',[0.77 0.03 0.12 0.04],...
 'Value',1,...
 'String','1|2|3|4');
uicontrol(f,'Style','Pushbutton',...
 'BackGroundColor',[0.9 0.9 0.9],...
 'Fontsize',7,...
 'Units','normalized',...
 'Position',[0.9 0.03 0.09 0.04],...
 'String','Fit',...
 'Callback',['ICAfit']);
%-----------------------------------------

% Save and load regions
uicontrol(f,'Style','push',...
 'String','save reg 1','Units','normalized',...
 'Position',[0.06 0.45 0.22 0.04],'Callback',['R1(1)=str2num(get(tr1bx,''String''));,',...
 'R1(2)=str2num(get(tr1by,''String''));,',...
 'R1(3)=str2num(get(tr1bdx,''String''));,',...
 'R1(4)=str2num(get(tr1bdy,''String''));,',...
 'save region1 R1']);
uicontrol(f,'Style','push',...
 'String','load reg 1','Units','normalized',...
 'Position',[0.06 0.4 0.22 0.04],'Callback',['load region1;,',...
 'set(tr1bx,''String'',num2str(R1(1)));,',...
 'set(tr1by,''String'',num2str(R1(2)));,',...
 'set(tr1bdx,''String'',num2str(R1(3)));,',...
 'set(tr1bdy,''String'',num2str(R1(4)));']);

uicontrol(f,'Style','push',...
 'String','save reg 2','Units','normalized',...
 'Position',[0.06 0.32 0.22 0.04],'Callback',['R2(1)=str2num(get(tr2bx,''String''));,',...
 'R2(2)=str2num(get(tr2by,''String''));,',...
 'R2(3)=str2num(get(tr2bdx,''String''));,',...
 'R2(4)=str2num(get(tr2bdy,''String''));,',...
 'save region2 R2']);
uicontrol(f,'Style','push',...
 'String','load reg 2','Units','normalized',...
 'Position',[0.06 0.27 0.22 0.04],'Callback',['load region2;,',...
 'set(tr2bx,''String'',num2str(R2(1)));,',...
 'set(tr2by,''String'',num2str(R2(2)));,',...
 'set(tr2bdx,''String'',num2str(R2(3)));,',...
 'set(tr2bdy,''String'',num2str(R2(4)));']);

uicontrol(f,'Style','push',...
 'String','save reg 3','Units','normalized',...
 'Position',[0.06 0.19 0.22 0.04],'Callback',['R3(1)=str2num(get(tr3bx,''String''));,',...
 'R3(2)=str2num(get(tr3by,''String''));,',...
 'R3(3)=str2num(get(tr3bdx,''String''));,',...
 'R3(4)=str2num(get(tr3bdy,''String''));,',...
 'save region3 R3']);
uicontrol(f,'Style','push',...
 'String','load reg 3','Units','normalized',...
 'Position',[0.06 0.14 0.22 0.04],'Callback',['load region3;,',...
 'set(tr3bx,''String'',num2str(R3(1)));,',...
 'set(tr3by,''String'',num2str(R3(2)));,',...
 'set(tr3bdx,''String'',num2str(R3(3)));,',...
 'set(tr3bdy,''String'',num2str(R3(4)));']);
%--------------------------------------------------