f = figure(1);
set(f,'Position',[100 500 800 300]);
AX=axes; set (AX,'Position',[0.05 0.08 0.55 0.85]);

t=(1:800)/100;

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.65 0.92 0.05 0.05],...
    'String','a1',...
    'FontSize',8);
a1ED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.7 0.92 0.05 0.05],...
    'String','2',...
    'FontSize',8);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.77 0.92 0.05 0.05],...
    'String','a2',...
    'FontSize',8);
a2ED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.82 0.92 0.05 0.05],...
    'String','3.1',...
    'FontSize',8);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.89 0.92 0.05 0.05],...
    'String','a3',...
    'FontSize',8);
a3ED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.94 0.92 0.05 0.05],...
    'String','2',...
    'FontSize',8);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.65 0.85 0.05 0.05],...
    'String','b1',...
    'FontSize',8);
b1ED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.7 0.85 0.05 0.05],...
    'String','6',...
    'FontSize',8);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.77 0.85 0.05 0.05],...
    'String','b2',...
    'FontSize',8);
b2ED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.82 0.85 0.05 0.05],...
    'String','1.5',...
    'FontSize',8);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.89 0.85 0.05 0.05],...
    'String','b3',...
    'FontSize',8);
b3ED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.94 0.85 0.05 0.05],...
    'String','12',...
    'FontSize',8);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.65 0.78 0.05 0.05],...
    'String','c',...
    'FontSize',8);
cED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.7 0.78 0.05 0.05],...
    'String','0.03',...
    'FontSize',8);

uicontrol(f,'Style','push',...
 'String','multisigm','Units','normalized',...
 'Position',[0.8 0.78 0.1 0.05],'Callback',['a1=str2num(get(a1ED,''String''));,',...
 'a2=str2num(get(a2ED,''String''));,',...
 'a3=str2num(get(a3ED,''String''));,',...
 'b1=str2num(get(b1ED,''String''));,',...
 'b2=str2num(get(b2ED,''String''));,',...
 'b3=str2num(get(b3ED,''String''));,',...
 'c=str2num(get(cED,''String''));,',...
 'F2=Sigmoid3(t,a1,a2,a3,b1,b2,b3,c);  dF2=F2(2:end)-F2(1:end-1); dF2=dF2/max(dF2);,',...
 'axes(AX), plot(t,F2/max(F2),t(1:end-1),dF2);']);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.65 0.68 0.05 0.05],...
    'String','init',...
    'FontSize',8);
initED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.7 0.68 0.05 0.05],...
    'String','0.8',...
    'FontSize',8);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.8 0.68 0.05 0.05],...
    'String','slope',...
    'FontSize',8);
slopED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.85 0.68 0.05 0.05],...
    'String','0.28',...
    'FontSize',8);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.65 0.61 0.05 0.05],...
    'String','ampl',...
    'FontSize',8);
amplED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.7 0.61 0.05 0.05],...
    'String','0.04',...
    'FontSize',8);
uicontrol(f,'Style','push',...
 'String','gauss','Units','normalized',...
 'Position',[0.8 0.61 0.1 0.05],'Callback',['init=str2num(get(initED,''String''));,',...
 'slop=str2num(get(slopED,''String''));,',...
 'ampl=str2num(get(amplED,''String''));,',...
 'F1=t*0; F1(round(init*100):end)=ampl*(1-exp(-slop*(t(round(init*100):end)-init).^2));dF1=F1(2:end)-F1(1:end-1); dF1=dF1/max(dF1);,',...
 'axes(AX), plot(t,F1/max(F1),t(1:end-1),dF1);']);

uicontrol(f,'Style','push',...
 'String','NaSim','Units','normalized',...
 'Position',[0.65 0.5 0.1 0.07],'Callback',['init=str2num(get(initED,''String''));,',...
 'slop=str2num(get(slopED,''String''));,',...
 'ampl=str2num(get(amplED,''String''));,',...
 'F1=t*0; F1(round(init*100):end)=ampl*(1-exp(-slop*(t(round(init*100):end)-init).^2));,',...
 'a1=str2num(get(a1ED,''String''));,',...
 'a2=str2num(get(a2ED,''String''));,',...
 'a3=str2num(get(a3ED,''String''));,',...
 'b1=str2num(get(b1ED,''String''));,',...
 'b2=str2num(get(b2ED,''String''));,',...
 'b3=str2num(get(b3ED,''String''));,',...
 'c=str2num(get(cED,''String''));,',...
 'F2=Sigmoid3(t,a1,a2,a3,b1,b2,b3,c); ,',...
 'F=F1+F2; dF=F(2:end)-F(1:end-1); dF=dF/max(dF);,',...
 'axes(AX), plot(t,F/max(F),t(1:end-1),dF);']);

durED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.87 0.5 0.05 0.07],...
    'String','8',...
    'FontSize',8);
uicontrol(f,'Style','push',...
 'String','duration','Units','normalized',...
 'Position',[0.77 0.5 0.1 0.07],'Callback',['dur=str2num(get(durED,''String''));,',...
 'fine=round(dur*100); t=(1:fine)/100;']);


linED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.75 0.05 0.05 0.1],...
    'String','99',...
    'FontSize',8);
uicontrol(f,'Style','push',...
 'String','load','Units','normalized',...
 'Position',[0.65 0.05 0.1 0.1],'Callback',['load linesignal;,',...
 'load linesignal;,',...
 'radius=linesignal/pi;,',...
 'volum=(radius.*radius)*pi*0.5;,',...
 'load Vm;,',...
 'duration=size(linesignal,2);,',...
 'dur=duration/10; set(durED,''String'',num2str(duration));,',...
 'tt=(1:size(linesignal,2))/10; PosInd=str2num(get(linED,''String''));,',...
 'axes(AX), plot(tt,linesignal(str2num(get(linED,''String'')),:));']);

uicontrol(f,'Style','push',...
 'String','normalised','Units','normalized',...
 'Position',[0.75 0.2 0.08 0.1],'Callback',['init=str2num(get(initED,''String''));,',...
 'slop=str2num(get(slopED,''String''));,',...
 'ampl=str2num(get(amplED,''String''));,',...
 'F1=t*0; F1(round(init*100):end)=ampl*(1-exp(-slop*(t(round(init*100):end)-init).^2));,',...
 'a1=str2num(get(a1ED,''String''));,',...
 'a2=str2num(get(a2ED,''String''));,',...
 'a3=str2num(get(a3ED,''String''));,',...
 'b1=str2num(get(b1ED,''String''));,',...
 'b2=str2num(get(b2ED,''String''));,',...
 'b3=str2num(get(b3ED,''String''));,',...
 'c=str2num(get(cED,''String''));,',...
 'F2=Sigmoid3(t,a1,a2,a3,b1,b2,b3,c); ,',...
 'F=F1+F2; dF=F(2:end)-F(1:end-1); dF=dF/max(dF);,',...
 'load linesignal;,',...
 'duration=size(linesignal,2);,',...
 'dur=duration/10; set(durED,''String'',num2str(duration));,',...
 'tt=(1:size(linesignal,2))/10; mass=mean(linesignal(str2num(get(linED,''String'')),end-8:end));,',...
 'axes(AX), plot(t,F/max(F),t(1:end-1),dF,tt,linesignal(str2num(get(linED,''String'')),:)/mass);']);

uicontrol(f,'Style','push',...
 'String','together','Units','normalized',...
 'Position',[0.65 0.2 0.08 0.1],'Callback',['init=str2num(get(initED,''String''));,',...
 'slop=str2num(get(slopED,''String''));,',...
 'ampl=str2num(get(amplED,''String''));,',...
 'F1=t*0; F1(round(init*100):end)=ampl*(1-exp(-slop*(t(round(init*100):end)-init).^2));,',...
 'a1=str2num(get(a1ED,''String''));,',...
 'a2=str2num(get(a2ED,''String''));,',...
 'a3=str2num(get(a3ED,''String''));,',...
 'b1=str2num(get(b1ED,''String''));,',...
 'b2=str2num(get(b2ED,''String''));,',...
 'b3=str2num(get(b3ED,''String''));,',...
 'c=str2num(get(cED,''String''));,',...
 'F2=Sigmoid3(t,a1,a2,a3,b1,b2,b3,c); ,',...
 'F=F1+F2; dF=F(2:end)-F(1:end-1); dF=dF/max(dF);,',...
 'load linesignal;,',...
 'duration=size(linesignal,2);,',...
 'dur=duration/10; set(durED,''String'',num2str(duration));,',...
 'tt=(1:size(linesignal,2))/10; mass=mean(linesignal(str2num(get(linED,''String'')),end-8:end));,',...
 'Fcalib=F*100*0.175; Nions=Fcalib*volum(PosInd)*6.02*100000;,',...
 'dNions=Nions(2:end)-Nions(1:end-1); dNions=dNions*0.0016*1.6;,',...
 'axes(AX), plot(tt,resample(F,1,10),tt,linesignal(str2num(get(linED,''String'')),:));']);


uicontrol(f,'Style','push',...
 'String','smoothder','Units','normalized',...
 'Position',[0.82 0.05 0.08 0.1],'Callback',['init=str2num(get(initED,''String''));,',...
 'slop=str2num(get(slopED,''String''));,',...
 'ampl=str2num(get(amplED,''String''));,',...
 'F1=t*0; F1(round(init*100):end)=ampl*(1-exp(-slop*(t(round(init*100):end)-init).^2));,',...
 'a1=str2num(get(a1ED,''String''));,',...
 'a2=str2num(get(a2ED,''String''));,',...
 'a3=str2num(get(a3ED,''String''));,',...
 'b1=str2num(get(b1ED,''String''));,',...
 'b2=str2num(get(b2ED,''String''));,',...
 'b3=str2num(get(b3ED,''String''));,',...
 'c=str2num(get(cED,''String''));,',...
 'F2=Sigmoid3(t,a1,a2,a3,b1,b2,b3,c); ,',...
 'F=F1+F2; dF=F(2:end)-F(1:end-1); dF=dF/max(dF);,',...
 'load linesignal;,',...
 'duration=size(linesignal,2);,',...
 'dur=duration/10; set(durED,''String'',num2str(duration));,',...
 'tt=(1:size(linesignal,2))/10; mass=mean(linesignal(str2num(get(linED,''String'')),end-8:end));,',...
 'relin=linesignal(str2num(get(linED,''String'')),:);'...
 'dfsig=relin(2:end)-relin(1:end-1);'...
 'smdf=smooth(dfsig,12,''sgolay'')'';'...
 'axes(AX), plot(tt,resample(dF,1,10)/max(dF),tt(1:end-1),smdf/max(smdf));']);

uicontrol(f,'Style','push',...
 'String','refit','Units','normalized',...
 'Position',[0.91 0.05 0.08 0.1],'Callback',['xf=t;'...
'yf=resample(linesignal(88,:),10,1);'...
'fittedcurve=fit(xf(:),yf(:),''c1.*(1./(1+exp(c2*(-x+c3)))).*(1./(1+exp(c4*(-x+c5)))).*(1./(1+exp(c6*(-x+c7))))+c8*(c9+exp(-c10*(x-c11).^4))'',''StartPoint'',[c,b1, a1,b2,a2,b3,a3,ampl,0.001,slop,init]);'...
'rofit=rot90(fittedcurve(t));'...
'coeffvals = coeffvalues(fittedcurve);'...
'set(initED,''String'',num2str(coeffvals(11)));'...
'set(slopED,''String'',num2str(coeffvals(10)));'...
'set(amplED,''String'',num2str(coeffvals(8)));'...
'set(a3ED,''String'',num2str(coeffvals(7)));'...
'set(b3ED,''String'',num2str(coeffvals(6)));'...
'set(a2ED,''String'',num2str(coeffvals(5)));'...
'set(b2ED,''String'',num2str(coeffvals(4)));'...
'set(a1ED,''String'',num2str(coeffvals(3)));'...
'set(b1ED,''String'',num2str(coeffvals(2)));'...
'set(cED,''String'',num2str(coeffvals(1)));'...
'axes(AX), plot(t,rofit,t,yf,t,F);']);


uicontrol(f,'Style','push',...
 'String','difference','Units','normalized',...
 'Position',[0.85 0.2 0.08 0.1],'Callback',['init=str2num(get(initED,''String''));,',...
 'slop=str2num(get(slopED,''String''));,',...
 'ampl=str2num(get(amplED,''String''));,',...
 'F1=t*0; F1(round(init*100):end)=ampl*(1-exp(-slop*(t(round(init*100):end)-init).^2));,',...
 'a1=str2num(get(a1ED,''String''));,',...
 'a2=str2num(get(a2ED,''String''));,',...
 'a3=str2num(get(a3ED,''String''));,',...
 'b1=str2num(get(b1ED,''String''));,',...
 'b2=str2num(get(b2ED,''String''));,',...
 'b3=str2num(get(b3ED,''String''));,',...
 'c=str2num(get(cED,''String''));,',...
 'F2=Sigmoid3(t,a1,a2,a3,b1,b2,b3,c); ,',...
 'F=F1+F2; dF=F(2:end)-F(1:end-1); dF=dF/max(dF);,',...
 'load linesignal;,',...
 'duration=size(linesignal,2);,',...
 'dur=duration/10; set(durED,''String'',num2str(duration));,',...
 'tt=(1:size(linesignal,2))/10; mass=mean(linesignal(str2num(get(linED,''String'')),end-8:end));,',...
 'axes(AX), plot(tt,linesignal(str2num(get(linED,''String'')),:)-resample(F,1,10));']);

parED=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.75 0.35 0.1 0.1],...
    'String','param1',...
    'FontSize',8);
uicontrol(f,'Style','push',...
 'String','save params','Units','normalized',...
 'Position',[0.65 0.35 0.09 0.1],'Callback',['init=str2num(get(initED,''String''));,',...
 'slop=str2num(get(slopED,''String''));,',...
 'ampl=str2num(get(amplED,''String''));,',...
 'a1=str2num(get(a1ED,''String''));,',...
 'a2=str2num(get(a2ED,''String''));,',...
 'a3=str2num(get(a3ED,''String''));,',...
 'b1=str2num(get(b1ED,''String''));,',...
 'b2=str2num(get(b2ED,''String''));,',...
 'b3=str2num(get(b3ED,''String''));,',...
 'c=str2num(get(cED,''String''));,',...
 'eval([''save '',get(parED,''String''),'' a1 a2 a3 b1 b2 b3 c slop ampl init'']);']);
uicontrol(f,'Style','push',...
 'String','load params','Units','normalized',...
 'Position',[0.86 0.35 0.09 0.1],'Callback',['eval([''load '',get(parED,''String''),'' ;'']);,',...
 'set(initED,''String'',num2str(init));,',...
 'set(slopED,''String'',num2str(slop));,',...
 'set(amplED,''String'',num2str(ampl));,',...
 'set(a1ED,''String'',num2str(a1));,',...
 'set(a2ED,''String'',num2str(a2));,',...
 'set(a3ED,''String'',num2str(a3));,',...
 'set(b1ED,''String'',num2str(b1));,',...
 'set(b2ED,''String'',num2str(b2));,',...
 'set(b3ED,''String'',num2str(b3));,',...
 'set(cED,''String'',num2str(c));']);