function redshirt_read_dual(n)

% This function converts n consecutive files generated by neuroCCD camera (redshirt) into
% matlab files starting from the selected one.
% Matlab files contains four variables:
% A: a 5 elements array containing information on the recording:
%   A(1): number of frames
%   A(2): number of columns
%   A(3): number of rows
%   A(4): frame interval
%   A(5): ratio between frame interval and electrical sampling time
% y: electrical signal
% M: Average image 
% Y: Y image sequence (A(2)*A(3)*A(1) matrix)
     

[file perc]=uigetfile('*.da','load redshirt data file');
fn=str2num(file(1,end-4:end-3));
for k=fn:fn+n-1,
   ds=num2str(k);
   if length(ds)==1,
      ds=['0',ds];
   end
   file1(k-fn+1,:)=[file(1,1:end-5),ds,file(1,end-2:end)];
end   

for k=1:n,
   file=file1(k,:);
   display(file);
   
Y=0;
y=0;
    [fp,emsg]=fopen(file,'r');
     if (fp <= 2), 
    	disp(emsg), 
     return,
    end   
    AA=fread(fp,[1,2560],'int16'); %read the header
    A(1)=AA(5); %number of frames
    A(2)=AA(385); %number of columns
    A(3)=AA(386); %number of rows
    A(4)=AA(389)/1000; %frame interval
    if A(4)>=10,
        A(4)=A(4)*AA(391);
    end
    A(5)=AA(392); %Acquisition ratio
    if A(5)==0,
        A(5)=1;
    end
    
    YY=ones(A(3),A(2),A(1));
    for kk=0:A(1)-1
        %kk
        fseek(fp,5120+kk*2,-1);
        Y=fread(fp,[1,A(2)*A(3)],'int16',A(1)*2-2);
        for k=0:A(3)-1, YY(k+1,1:A(2),kk+1)=Y((1:A(2))+A(2)*k); end
    end    
    Y=YY;
    y=fread(fp,[A(1),8],'int16');
    D=fread(fp,[A(3),A(2)],'int16');
    fclose(fp);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    y=0;
    [fp,emsg]=fopen(file,'r');
    if (fp <= 2), 
    	disp(emsg), 
      return,
    end   
    AA=fread(fp,[1,2560],'int16'); %read the header
    A(1)=AA(5); %number of frames
    A(2)=AA(385); %number of columns
    A(3)=AA(386); %number of rows
    A(4)=AA(389)/1000; %frame interval
    if A(4)>=10,
        A(4)=A(4)*AA(391);
    end
    A(5)=AA(392); %Acquisition ratio
    if A(5)==0,
        A(5)=1;
    end
    
    fseek(fp,A(1)*A(2)*A(3)*2,'cof'); 
    y=fread(fp,[A(1)*A(5),1],'int16');
    y=y*2000/65535;
    fclose(fp);
    if A(2)==26,
       YY=ones(80,160,A(1));
       for k=0:2,
          for kk=0:2,
             YY(2+k:3:77+k,2+kk:3:77+kk,:)=Y;
          end   
       end   
    end 
    Y=YY;
    M=mean(Y,3); M=M/max(max(M));
            
    file=file(1:end-3);
    eval(['save ',file,' Y y A M;']);
    
end    